name: Scheduled page check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm install
      - name: Create screenshots directory
        run: mkdir -p screenshots
      - name: Run script
        run: npm start
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHECK_VENUES: phs,trainerlisten
          DEBUG: true
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: my-screenshots
          path: screenshots/
          retention-days: 1  # Optional, defaults to 90 days
