name: Scheduled page check

on:
  schedule:
    - cron: '10,25,40,55 6-20 * * *'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm start
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHECK_VENUES: phs,halle 2,halle 3
          DEBUG: true
